AttachSpec("../spec");

function LoadForm(d,p,lvl_label, evals : HeckeBd := 30)
    // Helper function to load form from value of d, p, the level label, and eigenvalues evals
    // WARNING: this recomputes eigenforms, so it's expensive - it's better to use something else
    F := QuadFld(d);
    lvl := LMFDBIdeal(F, lvl_label);
    W := BianchiWeight(F, 0,0 : char := p);
    B := BianchiCohomologySpace(lvl, W);
    form := 0;
    good_primes := GoodHeckePrimes(B, HeckeBd);
    SetHeckeBound(B, HeckeBd);
    len := Min(#good_primes, #evals);
    // if Dimension(B) eq 1 then
    // 	form := Basis(B)[1];
    // 	form`isEigenform := true;
    // 	return form;
    // end if;
    for f in Eigenforms(B) do
	found := false;
	for i -> ev in evals[1..len] do
	    if ev ne 0 and ev ne EigenvalueList(f)[i] then 
		break;
	    end if;
	end for;
	form := f;
	break;
    end for;
    
    if Type(form) eq Type(0) then
	return "Eigenform not found";
    else
	return form;
    end if;
end function;


function FindLifts(f : lvlLowerBd := 0, lvlBd := 1000000 , at_p := false, includeLvl := false)
    LR_nums := LevelRaiseFactors(f, Min(Floor(lvlBd/Norm(Level(f))), 4000));
    // LR_nums := LevelRaisingPrimes(f);
    // LR_nums cat:= [P[1] : P in Factorization(Parent(f)`level * Characteristic(Parent(f)))];

    if #LR_nums eq 0 then
	return "No level raising primes available";
    else
	print "Level raise factors are", [LMFDBLabel(I) : I in LR_nums];
    end if;
    
    B := Parent(f);
    level1 := Level(B);
    ZZx<x> := PolynomialRing(Integers());
    K<Kgen> := NumberField(B);
    _, levelgen := IsPrincipal(level1);
    print "Level generated by", K!levelgen, "where Kgen satisfies", MinimalPolynomial(Kgen);

    ZK := Integers(K);
    Wp := Weight(B);
    W0 := BianchiWeight(K, 0,0);
    p := Characteristic(B);
    // Only check at primes above p
    if at_p then
	LR_nums := [];
	for fac in Factorization(p*ZK) do
	    Append(~LR_nums, fac[1]);
	    Append(~LR_nums, fac[1]^2);
	end for;
	LR_nums := SortByLMFDBLabel(LR_nums);
    end if;
    
    if includeLvl then
	Append(~LR_nums, 1*ZK);
	LR_nums := SortByLMFDBLabel(LR_nums);
    end if;

    HeckeField := HeckeField(f);
    
    // Caching is supposed to speed this up by storing oldspaces
    // see https://magma.maths.usyd.edu.au/magma/handbook/text/1784#20376
    SetStoreModularForms(K, true);
    // print "Factors are", [LMFDBLabel(I) : I in LR_nums];
    for I in LR_nums do
	level2 := I*level1;
	if Norm(level2) gt lvlBd or Norm(level2) lt lvlLowerBd then
	    print "Skipping level", LMFDBLabel(I), "since not in range specified by lvlLowerBd and lvlBd";
	    continue;
	end if;
	_, princ := IsPrincipal(I);
	print "Looking for lifts with level", LMFDBLabel(I), "=", K!princ, "added; new level is", LMFDBLabel(level2);
	// print "Can kill lifting obstruction?", CanKillLiftingObstr(p, level2,level1);
	// B0 := BianchiCohomologySpace(level2, W0);
	// Bp := BianchiCohomologySpace(level2, Wp);
	// red_map := ReductionModPMap(B0,Bp);
	// reduction := [Bp`down(red_map((Inverse(B0`down)(v)))) : v in Basis(B0`forms)];
	// oldspace := DegenerateSubspace(f, Bp);
        // inter := sub<Bp`forms | reduction> meet oldspace;

	// if Dimension(inter) gt 0 then
	//     print "Found intersection of oldspace and reduction mod p in level", LMFDBLabel(level2);
	// end if;
	primes := SortByLMFDBLabel(Setseq(Keys(Eigenvalues(f))));
	primes := [qq : qq in primes | IsCoprime(qq,level2)];
	C := BianchiCuspForms(K, level2);
	if Dimension(C) eq 0 then
	    print "Characteristic 0 space empty";
	end if;
	print "Computing eigenforms, this may take time";
	
	for j -> F in NewformDecomposition(NewSubspace(C)) do
	    print "Testing eigenform", j;
	    // Compute first Hecke eigenvalue to find field
	    E := Parent(HeckeEigenvalue(Eigenform(F), primes[1]));
	    if Degree(E) gt 1 then
		E<z> := Parent(HeckeEigenvalue(Eigenform(F), primes[1]));
	    else
		z := Rationals()!1;
	    end if;
	    
	    if Degree(E) lt Degree(HeckeField) then
		print "Degree of char 0 eigenvalue field is too small";
		continue;
	    end if;
	    
	    print "Eigenvalues of char 0 lift lie in", E, "of discriminant", Discriminant(Integers(E));
	    p_primes := [m[1] : m in Factorization(p*Integers(E))];
	    
	    for pp in p_primes do
		flag, prin := IsPrincipal(pp);
		Emodp_bad, phi_bad := ResidueClassField(pp);
		if flag then
		    print "Looking at reduction modulo", E!prin, "of residue degree", Degree(Emodp_bad);
		else
		    print "Looking at reduction modulo non-principal ideal above", p;
		end if;
		
		// Get better presentation of finite field than the default one:
		if Degree(Emodp_bad) gt 1 then
		    Fpx := PolynomialRing(GF(p));
		    if not exists(EmodpPol){ fac[1] : fac in Factorization(Fpx!MinimalPolynomial(z)) | Degree(fac[1]) eq Degree(Emodp_bad)} then
			print "Minimal polynomial does not have factor of correct size", [Degree(fac[1]) : fac in Factorization(Fpx!MinimalPolynomial(z))];
			continue;
		    end if;
		    Emodp<w> := ext<GF(p) | EmodpPol>;
		    assert #Emodp eq #Emodp_bad;
		    flag, Eiso := IsIsomorphic(Emodp_bad, Emodp);
		    phi := phi_bad*Eiso;
		    SetPowerPrinting(Emodp, false);
		else
		    EmodpPol := "x-1";
		    Emodp := Emodp_bad;
		    phi := phi_bad;
		end if;

		if Degree(Emodp) eq Degree(HeckeField) then
		    // this is chosen at random goddammit
		    flag, emb := IsIsomorphic(HeckeField, Emodp);
		    assert flag;
		    _, auts, _ := AutomorphismGroup(Emodp);
		elif Degree(Emodp) mod Degree(HeckeField) eq 0 then
		    Embed(HeckeField, Emodp);
		    emb := hom<HeckeField -> Emodp | x :-> Emodp!x>;
		    _, auts, _ := AutomorphismGroup(Emodp);
		else
		    print "Wrong residue degree of prime";
		    continue;
		end if;
		
		// Need to loop over automorphisms because iso is chosen at random
		for aut_no -> aut in auts do
		    wrong_ctr := 0;
		    is_wrong := false;
		    print "Testing automorphism", aut_no;
		    i := emb*aut;
		    for qq in primes do
			_, qq_gen := IsPrincipal(qq);
			
			if i(Eigenvalue(f,qq)) ne phi(HeckeEigenvalue(Eigenform(F), qq)) then
			    // This is not the right one, so move on to another level raising prime;
			    // but we will allow a couple of mismatches just in case.
			    wrong_ctr +:= 1;
			    print "Hecke eigenvalues don't agree for", LMFDBLabel(qq);
			    
			    if wrong_ctr gt 5 then
				is_wrong := true;
				wrong_ctr := 0;
				print "Eigenvalues didn't match, moving to next";
				continue aut;
			    end if;
			else
			    print "Hecke eigenvalues agree for", LMFDBLabel(qq);
			end if;
		    end for;
		    if not is_wrong then 
			print "Found correct form!";
			printf "Using prime above %o corresponding to mod p factor %o of minimal polynomial %o\n", p, EmodpPol, MinimalPolynomial(z);
			colNum := #primes;
			labels := ["$\\mathfrak{p}$"] cat [Sprint(LMFDBLabel(pp)) : pp in primes[1..colNum]];
			fp_evals := ["$a_{\\mathfrak{p}}(f)$"] cat ListToEquationStrings([i(Eigenvalue(f,pp)) : pp in primes[1..colNum]]);
			Fp_evals := ["$a_{\\mathfrak{p}}(F) \\mod p$"] cat ListToEquationStrings([phi(HeckeEigenvalue(Eigenform(F),pp)) : pp in primes[1..colNum]]); 
			F_evals := ["$a_{\\mathfrak{p}}(F)$"] cat ListToEquationStrings([HeckeEigenvalue(Eigenform(F),pp) : pp in primes[1..colNum]]);
			print ListsToLatexTable([labels,fp_evals,Fp_evals, F_evals]);
			return F;
		    end if;

		end for;
	    end for;
	end for;
	print "---\n";
	// return inter;

    end for;
    return "None found";
end function;



/*
Attempts to find lifts of Bianchi cohomology class with irrational coefficients which is given as a string in the format

127.1;7;[ 1, 4 ];[ 1, 2 ];[ 5, 2 ];[ 5, 2 ];[ 0, 3 ];x^2 + 6*x + 3

where 
- the first entry is the level
- the second is the prime p,
- the last entry is the characteristic polynomial of the extension in which the Hecke eigenvalues lie
- the rest of the entries correspond to Hecke eigenvalues
*/

function BatchFindIrrationalLifts(d : lvlBd := 100)
    F := QuadFld(d);
    filename := "data/nonEis_d" cat Sprint(d) cat ".csv";
    lines := Split(Read(filename), "\n");
    header := Split(lines[1], ";");
    primeLabels := header[3..#header-1];
    primeList := [LMFDBIdeal(F,label) : label in primeLabels];

    for line in lines[2..#lines] do
	entries := Split(line, ";");
	if "x" notin entries[#entries] or forall{ 1 : e in entries[3..#entries-1] | "[" notin e} then
	    continue;
	end if;

	lvl := LMFDBIdeal(F, entries[1]);
	p := StringToInteger(entries[2]);
	// skip small primes
	if p eq 2 then continue; end if;
	
	B := BianchiCohomologySpace(lvl, BianchiWeight(F,0,0 : char :=p));
	f := ReadClass(line, B, primeList);
	print "Finding lifts for", f, "; this may take time";
	f0 := FindLifts(f : lvlBd := lvlBd, at_p := true);
	if Type(f0) eq Type("Foo") then
	    print f0;
	    // print "++++FOUND LIFT++++", f0;
	end if;
    end for;
    return 0;
end function;


/*
Helper function to load rational lifts.
*/

function LoadAllLifts(d : startBd := 0, stopBd := 1000)
    F := QuadFld(d);
    filename := "data/nonEis_d" cat Sprint(d) cat ".csv";
    lines := Split(Read(filename), "\n");
    header := Split(lines[1], ";");
    primeLabels := header[3..#header];
    primeList := [LMFDBIdeal(F,label) : label in primeLabels];
    forms := [* *];
    for i -> line in lines[2..#lines] do
	if i le startBd or i gt stopBd then continue; end if;

	entries := Split(line, ";");
	if "x" in entries[#entries] or "[" in entries[3] or exists{true : entry in entries | "w" in entry} then
	    continue;
	end if;

	lvl := LMFDBIdeal(F, entries[1]);
	p := StringToInteger(entries[2]);
	if p in [2,3] then continue; end if;

	B := BianchiCohomologySpace(lvl, BianchiWeight(F,0,0 : char :=p));
	f := ReadClass(line,B, primeList);
	Append(~forms,f);
    end for;
    return forms;
    
end function;


// Check whether p divides the index of Gamma0(J) in Gamma0(I).
// Heuristically, this is expected if the H^2 degeneracy map
// kills the lifting obstruction 
// NOTE: not sure if this is correct; in any case it seems to always return false, so WIP
function CanKillLiftingObstr(p, I,J)
    assert I subset J;
    primes := [pp : pp in Divisors(J) | IsPrime(pp) and IsCoprime(I,pp)];
    if primes ne [] then
	return Norm(J)/Norm(I)* &*primes subset Parent(I)!p;
    else
	return false;
    end if;
end function;

function CheckNonrationalLift(d, line, topLine: extended := false)
    F := QuadFld(d);
    lvl := Split(line, ";")[1];
    topList := Split(topLine, ";");
    primeList := topList[3..#topList];
    p := StringToInteger(Split(line, ";")[2]);
    B := BianchiCohomologySpace(LMFDBIdeal(F, lvl), BianchiWeight(F,0,0 : char := p));
    print "Initializing class from line";
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    print "Initialized class; looking for lifts";
    if not extended then
	return FindLifts(f);
    end if;
    
    fLift := FindLifts(f);

    newLvl := Level(fLift);
    B := BianchiCohomologySpace(newLvl, BianchiWeight(BaseField(fLift),0,0 : char := p));
    SetHeckeBound(B, 50);
    efs := Eigenforms(B);
    print "Exists multiplicity 2 mod p eigenspace of this level?", exists{ef : ef in efs | ef`eigenspaceDim eq 2};
    return fLift;
    
end function;

function CheckNR1()
    line := "281.2;5;[ 2, 1 ];[ 2, 3 ];[ 2, 2 ];[ 2, 1 ];[ 2, 0 ];[ 1, 0 ];[ 3, 1 ];[ 4, 3 ];0;[ 4, 1 ];[ 0, 2 ];[ 0, 0 ];[ 3, 0 ];[ 2, 0 ];[ 0, 1 ];[ 3, 3 ];[ 4, 2 ];[ 0, 1 ];[ 0, 3 ];[ 4, 3 ];[ 0, 1 ];[ 1, 3 ];[ 1, 0 ];x^2 + 4*x + 2";
    topLine := "level;p;2.1;2.2;7.1;9.1;11.1;11.2;23.1;23.2;25.1;29.1;29.2;37.1;37.2;43.1;43.2;53.1;53.2;67.1;67.2;71.1;71.2;79.1;79.2";

    return CheckNonrationalLift(7, line, topLine : extended := true);
end function;
    
// Check that ethereal form with Fp^2 coefficients lifts to a form when adding 5.1 to the level.
function CheckNonrationalLiftFp2()
    line := "293.1;3;[ 1, 1 ];[ 2, 0 ];[ 0, 0 ];0;[ 2, 1 ];[ 2, 1 ];[ 0, 2 ];[ 2, 1 ];[ 0, 1 ];[ 2, 2 ];[ 1, 1 ];[ 0, 1 ];[ 2, 0 ];[ 2, 1 ];[ 0, 2 ];[ 0, 1 ];[ 1, 0 ];[2, 0 ];[ 2, 2 ];[ 0, 0 ];[ 0, 0 ];[ 0, 2 ];[ 2, 2 ];[ 1, 2 ];[ 2, 2 ];x^2 + 1";
    primeList := "level;p;2.1;5.1;5.2;9.1;13.1;13.2;17.1;17.2;29.1;29.2;37.1;37.2;41.1;41.2;49.1;53.1;53.2;61.1;61.2;73.1;73.2;89.1;89.2;97.1;97.2";
    
    return CheckNonrationalLift(1, line, primeList);
end function;

function CheckAnotherNonrationalLiftFp2()
    F := QuadFld(11);
    p := 7;
    line := "124.1;7;[ 4, 1 ];[ 0, 5 ];0;[ 2, 6 ];[ 3, 4 ];[ 4, 2 ];[ 1, 1 ];[ 4, 2 ];0;[ 3, 4 ];[ 6, 6 ];[ 1, 2 ];[ 1, 0 ];[ 2, 3 ];0;[ 0, 6 ];[ 0, 4 ];[ 4, 1 ];[ 3, 1 ];[ 5, 0 ];[ 3, 3 ];[ 5, 6 ];[ 1, 0 ];[ 4, 2 ];[ 3, 4 ];[ 6, 2 ];[ 0, 4 ];x^2 + 6*x + 3";
    primeList := Split("3.1;3.2;4.1;5.1;5.2;11.1;23.1;23.2;31.1;31.2;37.1;37.2;47.1;47.2;49.1;53.1;53.2;59.1;59.2;67.1;67.2;71.1;71.2;89.1;89.2;97.1;97.2", ";");
    B := BianchiCohomologySpace(LMFDBIdeal(F,"124.1"), BianchiWeight(F,0,0 : char := p));
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    // return FindLifts(f);
    return FindLifts(f);
   
end function;

function CheckCubicNonrationalLift()
    d := 11;
    F := QuadFld(d);
    p := 3;
    bound := 250;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "265.1"), BianchiWeight(F,0,0 : char := p));
    // B := BianchiCohomologySpace(LMFDBIdeal(F, "355.1"), BianchiWeight(F,0,0 : char := p));
    SetHeckeBound(B, bound);
    for f in Eigenforms(B) do
	FindLifts(f : lvlBd := bound, at_p := true);
    end for;
    return "cope";

end function;

// function CheckNonRationalLift5()
//     line := "281.2;5;[ 2, 1 ];[ 2, 3 ];[ 2, 2 ];[ 2, 1 ];[ 2, 0 ];[ 1, 0 ];[ 3, 1 ];[ 4, 3 ];0;[ 4, 1 ];[ 0, 2 ];[ 0, 0 ];[ 3, 0 ];[ 2, 0 ];[ 0, 1 ];[ 3, 3 ];[ 4, 2 ];[ 0, 1 ];[ 0, 3 ];[ 4, 3 ];[ 0, 1 ];[ 1, 3 ];[ 1, 0 ];x^2 + 4*x + 2"
// end function;

function CheckMultiplicityWeird()
    // TODO: check that there's nothing at same level!
    p := 11;
    F := QuadFld(2);
    line := "89.2;11;1;8;7;0;0;9;10;0;10;9;1;8;4;2;8;6;10;7;2;0;6;4;4;8;0;6;6";
    primeList := Split("2.1;3.1;3.2;11.1;11.2;17.1;17.2;19.1;19.2;25.1;41.1;41.2;43.1;43.2;49.1;59.1;59.2;67.1;67.2;73.1;73.2;83.1;83.2;89.1;89.2;97.1;97.2", ";");
    B := BianchiCohomologySpace(LMFDBIdeal(F, "89.2"), BianchiWeight(F,0,0 : char := p));
    
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    fLift := FindLifts(f);

    newLvl := Level(fLift);
    B := BianchiCohomologySpace(newLvl, BianchiWeight(BaseField(fLift),0,0 : char := p));
    efs := Eigenforms(B);
    assert efs[1]`eigenspaceDim eq 2;
    return 0;
end function;

function CheckLiftableD2()
    p := 41;
    F := QuadFld(2);
    line := "97.1;41;15;11;1;23;39;39;11;33;12;11;0;0;27;35;31;35;29;5;40;22;12;2;30;9;23;0;5";
    primeList := Split("2.1;3.1;3.2;11.1;11.2;17.1;17.2;19.1;19.2;25.1;41.1;41.2;43.1;43.2;49.1;59.1;59.2;67.1;67.2;73.1;73.2;83.1;83.2;89.1;89.2;97.1;97.2", ";");
    B := BianchiCohomologySpace(LMFDBIdeal(F, "97.1"), BianchiWeight(F,0,0 : char := p));
    
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    return FindLifts(f : lvlBd := 200);
end function;

// Look for lifts which sage couldn't find in the lmfdb
function LookForLMFDBUnliftable(d)
    input := "data/lmfdbNonLift_d" cat Sprint(d) cat ".csv";
    output := "data/irrat_lifts_d" cat Sprint(d) cat ".csv";
    lines := Split(Read(input), "\n");
    topLine := lines[1];
    results := [* *];
    for line in lines[2..#lines] do
	print "Looking for lifts of line", line;
	res := CheckNonrationalLift(d, line, topLine);
	id := Split(line, ";")[1] cat ";" cat Split(line, ";")[2] cat ";";
	// if Sprint(res) eq "None found" then
	fprintf output, id cat Sprint(res) cat "\n";
	    // else
	    // fprintf output, id cat Sprint(res);
	// end if;
	
    end for;
    return results;
end function;

function LookForAllIrrational(d)
    input := "data/nonEis_d" cat Sprint(d) cat ".csv";
    output := "data/irrat_lifts_d" cat Sprint(d) cat ".csv";
    lines := Split(Read(input), "\n");
    topLine := lines[1];
    results := [* *];
    for line in lines[2..#lines] do
	if "[" notin line then
	    continue;
	end if;
	
	id := Split(line, ";")[1] cat ";" cat Split(line, ";")[2] cat ";";
	if id in Read(output) then
	    continue;
	end if;
	print "Looking for lifts of id", id;
	try 
	    res := CheckNonrationalLift(d, line, topLine);
	catch err
	    print "Failed to initalize class with error", err;
	    continue line;
	end try;
	

	// if Sprint(res) eq "None found" then
	fprintf output, id cat Sprint(res) cat "\n";
	    // else
	    // fprintf output, id cat Sprint(res);
	// end if;
	
    end for;
    return results;
end function;


function CheckNonLR()
    // This doesn't have any level raising factors, at least up to norm 200
    d := 1;
    F := QuadFld(d);
    p := 23;
    bound := 200;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "281.1"), BianchiWeight(F,0,0 : char := p));
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    lifts := [* *];
    for f in Eigenforms(B) do
	Append(~lifts, <f, FindLifts(f : lvlBd := bound, at_p := true)>);
    end for;
    return lifts;
end function;

function CheckDouchebag()
    // This one has small level so it shouldn't be that hard to find lift
    d := 2;
    F := QuadFld(d);
    p := 19;
    bound := 200;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "73.2"), BianchiWeight(F,0,0 : char := p));
    print "Initialized", B;
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    lifts := [* *];
    for f in Eigenforms(B) do
	print "Eigenvalues:", PrintEigenvalues(f : bd := bound);
	Append(~lifts, <f, FindLifts(f : at_p := true, includeLvl := false)>);
    end for;
    return lifts;

end function;

function CheckDouchebag2( : recompute:=false, bound := 100)
    // This one has small level so it shouldn't be that hard to find lift
    d := 3;
    F := QuadFld(d);
    p := 17;
    label := "277.1";
    B := BianchiCohomologySpace(LMFDBIdeal(F, label), BianchiWeight(F,0,0 : char := p));
    if recompute then
	print "Initialized", B;
	SetHeckeBound(B, bound);
	print "Computing eigenforms with Hecke bound", bound;
	f := Eigenforms(B)[1];
    else
	filename := "data/nonEis_d" cat Sprint(d) cat ".csv";
	lines := Split(Read(filename), "\n");
	primeLine := Split(lines[1], ";");
	primeList := primeLine[3..#primeLine];
	for line in lines do
	    if Split(line, ";")[1] eq label then
		f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
		break;
	    end if;
	end for;

    end if;
    
    lift := FindLifts(f : at_p := false, includeLvl := false);
    return lift;
end function;

function CheckDouchebag3()
    // This one has small level so it shouldn't be that hard to find lift
    d := 11;
    F := QuadFld(d);
    p := 17;
    bound := 100;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "69.2"), BianchiWeight(F,0,0 : char := p));
    print "Initialized", B;
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    lifts := [* *];
    for f in Eigenforms(B) do
	print "Eigenvalues:", EigenvalueList(f);
	Append(~lifts, <f, FindLifts(f : lvlBd := 5000, at_p := false, includeLvl := false)>);
    end for;
    return lifts;

end function;

