
AttachSpec("../BMF/spec");
load "loading.m";

function FindLifts(f : lvlLowerBd := 0, lvlUpperBd := 1000000 , at_p := false, from_data := false, heckeBd := 100)
    // the `from_data` parameter lets us use level-raise primes we might have computed up to a larger bound.
    if from_data then
	K := Parent(f)`field;
	ZK := MaximalOrder(K);
	dd := Discriminant(K);
	if dd mod 4 eq 0 then
	    dd := dd div 4;
	end if;
	p := Characteristic(Parent(f));
	level := Level(f);
	// TODO: change this when we store data in one csv file rather than many files  
	f_file := "data/LR/" cat Sprint(-dd) cat "/" cat LMFDBLabel(level) cat "_" cat Sprint(p);
	labels := Split(Read(f_file));
	LR_primes := [LMFDBIdeal(K,str) : str in labels] cat [f[1] : f in Factorization(level*p)];
	LR_nums := [1*ZK];

	to_add := LR_primes;

	// we keep adding (up to the bound) until there's nothing left to add
	while #to_add ne 0 do 
	    new_to_add := [];
		for I in LR_nums do 
		    for J in to_add do 
			if Norm(I*J*level) le lvlUpperBd and not I*J in LR_nums then 
			    Append(~LR_nums,I*J);
			    Append(~new_to_add,J);
			end if;
		    end for;
		end for;
		to_add := new_to_add;
	end while;
	Remove(~LR_nums,1);

	nn := [Norm(u) : u in LR_nums];
	ParallelSort(~nn,~LR_nums);
    else 
	LR_nums := LevelRaiseFactors(f, Min(Floor(lvlUpperBd/Norm(Level(f))), 4000));
	// LR_nums := LevelRaisingPrimes(f);
	// LR_nums cat:= [P[1] : P in Factorization(Parent(f)`level * Characteristic(Parent(f)))];
    end if;

    if #LR_nums eq 0 then
	return "No level raising primes available";
    else
	print "Level raise factors are", [LMFDBLabel(I) : I in LR_nums];
    end if;
    
    B := Parent(f);
    level1 := Level(B);
    ZZx<x> := PolynomialRing(Integers());
    K<Kgen> := NumberField(B);
    _, levelgen := IsPrincipal(level1);
    print "Level generated by", K!levelgen, "where Kgen satisfies", MinimalPolynomial(Kgen);

    ZK := Integers(K);
    Wp := Weight(B);
    W0 := BianchiWeight(K, 0,0);
    p := Characteristic(B);
    // Only check at primes above p
    if at_p then
	LR_nums := [];
	for fac in Factorization(p*ZK) do
	    Append(~LR_nums, fac[1]);
	    Append(~LR_nums, fac[1]^2);
	end for;
	LR_nums := SortByLMFDBLabel(LR_nums);
    end if;
    
    HeckeField := HeckeField(f);
    
    // Caching is supposed to speed this up by storing eigenforms
    // see https://magma.maths.usyd.edu.au/magma/handbook/text/1784#20376
    // The main utility of this is when you're accessing the same space several times.
    // SetStoreModularForms(K, storeForms);
    // print "Factors are", [LMFDBLabel(I) : I in LR_nums];
    primes := SortByLMFDBLabel(PrimesUpTo(heckeBd, K));
    for I in LR_nums do
	level2 := I*level1;
	if Norm(level2) gt lvlUpperBd or Norm(level2) lt lvlLowerBd then
	    print "Skipping level", LMFDBLabel(I), "since not in range specified by lvlLowerBd and lvlUpperBd";
	    continue;
	end if;
	_, princ := IsPrincipal(I);
	print "Looking for lifts with level", LMFDBLabel(I), "=", K!princ, "added; new level is", LMFDBLabel(level2);

	C := BianchiCuspForms(K, level2);
	if Dimension(C) eq 0 then
	    print "Characteristic 0 space empty";
	    continue;
	end if;
	goodPrimes := [qq : qq in primes | IsCoprime(qq, level2)];
	
	// Test small Hecke operator:
	qq1 := goodPrimes[1];
	ev1 := Eigenvalue(f, qq1);
	Phi := MinimalPolynomial(HeckeOperator(C,qq1));
	if Evaluate(ChangeRing(Phi, Parent(ev1)), ev1) ne 0 then
	    print "Eigenvalue of", LMFDBLabel(qq1), "is not a root of char 0 Hecke polynomial; evaluates to", Evaluate(ChangeRing(Phi, Parent(ev1)), ev1);
	    continue;
	else
	    print "Eigenvalue of", LMFDBLabel(qq1), "is a root of char 0 Hecke polynomial --- computing newform decomposition.";
	end if;
	
	print "Computing eigenforms, this may take time";
	
	for j -> F in NewformDecomposition(NewSubspace(C)) do
	    print "Testing eigenform", j;
	    // Compute first Hecke eigenvalue to find field
	    E := Parent(HeckeEigenvalue(Eigenform(F), goodPrimes[1]));
	    if Degree(E) gt 1 then
		E<z> := Parent(HeckeEigenvalue(Eigenform(F), goodPrimes[1]));
	    else
		z := Rationals()!1;
	    end if;
	    
	    if Degree(E) lt Degree(HeckeField) then
		print "Degree of char 0 eigenvalue field is too small";
		continue;
	    end if;
	    
	    print "Eigenvalues of char 0 lift lie in", E, "of discriminant", Discriminant(Integers(E));
	    p_primes := [m[1] : m in Factorization(p*Integers(E))];
	    
	    for pp in p_primes do
		flag, prin := IsPrincipal(pp);
		Emodp_bad, phi_bad := ResidueClassField(pp);
		if flag then
		    print "Looking at reduction modulo", E!prin, "of residue degree", Degree(Emodp_bad);
		else
		    print "Looking at reduction modulo non-principal ideal above", p;
		end if;
		
		// Get better presentation of finite field than the default one:
		if Degree(Emodp_bad) gt 1 then
		    Fpx := PolynomialRing(GF(p));
		    if not exists(EmodpPol){ fac[1] : fac in Factorization(Fpx!MinimalPolynomial(z)) | Degree(fac[1]) eq Degree(Emodp_bad)} then
			print "Minimal polynomial does not have factor of correct size", [Degree(fac[1]) : fac in Factorization(Fpx!MinimalPolynomial(z))];
			continue;
		    end if;
		    Emodp<w> := ext<GF(p) | EmodpPol>;
		    assert #Emodp eq #Emodp_bad;
		    flag, Eiso := IsIsomorphic(Emodp_bad, Emodp);
		    phi := phi_bad*Eiso;
		    SetPowerPrinting(Emodp, false);
		else
		    EmodpPol := "x-1";
		    Emodp := Emodp_bad;
		    phi := phi_bad;
		end if;

		if Degree(Emodp) eq Degree(HeckeField) then
		    // this is chosen at random goddammit
		    flag, emb := IsIsomorphic(HeckeField, Emodp);
		    assert flag;
		    _, auts, _ := AutomorphismGroup(Emodp);
		elif Degree(Emodp) mod Degree(HeckeField) eq 0 then
		    Embed(HeckeField, Emodp);
		    emb := hom<HeckeField -> Emodp | x :-> Emodp!x>;
		    _, auts, _ := AutomorphismGroup(Emodp);
		else
		    print "Wrong residue degree of prime";
		    continue;
		end if;
		
		// Need to loop over automorphisms because iso is chosen at random
		for aut_no -> aut in auts do
		    wrong_ctr := 0;
		    is_wrong := false;
		    print "Testing automorphism", aut_no;
		    i := emb*aut;
		    for qq in goodPrimes do
			_, qq_gen := IsPrincipal(qq);
			
			if i(Eigenvalue(f,qq)) ne phi(HeckeEigenvalue(Eigenform(F), qq)) then
			    // This is not the right one, so move on to another level raising prime;
			    // but we will allow a couple of mismatches just in case.
			    wrong_ctr +:= 1;
			    print "Hecke eigenvalues don't agree for", LMFDBLabel(qq);
			    
			    if wrong_ctr gt 3 then
				is_wrong := true;
				wrong_ctr := 0;
				print "Eigenvalues didn't match, moving to next";
				continue aut;
			    end if;
			else
			    print "Hecke eigenvalues agree for", LMFDBLabel(qq);
			end if;
		    end for;
		    if not is_wrong then 
			print "Found correct form!";
			printf "Using prime above %o corresponding to mod p factor %o of minimal polynomial %o\n", p, EmodpPol, MinimalPolynomial(z);
			A := AssociativeArray();
			A["lift_level"] := LMFDBLabel(Level(F));
			A["Coeff_minpoly"] := Sprint(DefiningPolynomial(E));
			for pp in primes do
			    // Can only compute eigenvalues coprime to level in magma; so we pad with 0 (MAYBE: better default?)
			    A[LMFDBLabel(pp)] := IsCoprime(pp, Level(F)) select Sprint(Eltseq(HeckeEigenvalue(Eigenform(F), pp))) else "0";
			    end for;
			return A;
		    end if;

		end for;
	    end for;
	end for;
	print "---\n";
	// return inter;

    end for;
    return "None found";
end function;

/*
Helper function to load rational lifts.
*/

function LoadAllLifts(d : startBd := 0, stopBd := 1000)
    F := QuadFld(d);
    filename := "data/nonEis_d" cat Sprint(d) cat ".csv";
    lines := Split(Read(filename), "\n");
    header := Split(lines[1], ";");
    primeLabels := header[3..#header];
    primeList := [LMFDBIdeal(F,label) : label in primeLabels];
    forms := [* *];
    for i -> line in lines[2..#lines] do
	if i le startBd or i gt stopBd then continue; end if;

	entries := Split(line, ";");
	if "x" in entries[#entries] or "[" in entries[3] or exists{true : entry in entries | "w" in entry} then
	    continue;
	end if;

	lvl := LMFDBIdeal(F, entries[1]);
	p := StringToInteger(entries[2]);
	if p in [2,3] then continue; end if;

	B := BianchiCohomologySpace(lvl, BianchiWeight(F,0,0 : char :=p));
	f := ReadClass(line,B, primeList);
	Append(~forms,f);
    end for;
    return forms;
    
end function;

function CheckNonrationalLift(F, line, topLine : lvlLowerBd :=0, lvlUpperBd := 10000, recompute := false, heckeBd := 200)
    lvl := Split(line, ";")[1];
    topList := Split(topLine, ";");
    primeList := topList[3..#topList-3];
    print(primeList);
    p := StringToInteger(Split(line, ";")[2]);
    B := BianchiCohomologySpace(LMFDBIdeal(F, lvl), BianchiWeight(F,0,0 : char := p));
    
    print "Initializing class from line";

    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    print "Initialized class; looking for lifts";
    if recompute then
	print "Recomputing Hecke eigenvalues with Hecke bound", heckeBd;
	ComputeHeckeOperators(B);
	// extract correct recomputed eigenform
	// necessary because f doesn't have a vector (iirc)
	for f2 in Eigenforms(B) do
	    if forall{pp : pp in GoodHeckePrimes(B, 50) | MinimalPolynomial(Eigenvalue(f,pp)) eq MinimalPolynomial(Eigenvalue(f2,pp))}  then
		f := f2;
		print "Identified recomputed eigenform!";
		break;
	    end if;
	end for;
    end if;

    return FindLifts(f : lvlLowerBd := lvlLowerBd, lvlUpperBd := lvlUpperBd, heckeBd := heckeBd), f;
    
    
end function;

// Degree 6 Hecke field example
function CheckNR1()
    line := "281.2;5;[ 2, 1 ];[ 2, 3 ];[ 2, 2 ];[ 2, 1 ];[ 2, 0 ];[ 1, 0 ];[ 3, 1 ];[ 4, 3 ];0;[ 4, 1 ];[ 0, 2 ];[ 0, 0 ];[ 3, 0 ];[ 2, 0 ];[ 0, 1 ];[ 3, 3 ];[ 4, 2 ];[ 0, 1 ];[ 0, 3 ];[ 4, 3 ];[ 0, 1 ];[ 1, 3 ];[ 1, 0 ];x^2 + 4*x + 2";
    topLine := "level;p;2.1;2.2;7.1;9.1;11.1;11.2;23.1;23.2;25.1;29.1;29.2;37.1;37.2;43.1;43.2;53.1;53.2;67.1;67.2;71.1;71.2;79.1;79.2";

    return CheckNonrationalLift(QuadFld(7), line, topLine : extended := true);
end function;
    
// Check that ethereal form with Fp^2 coefficients lifts to a form when adding 5.1 to the level.
function CheckNonrationalLiftFp2()
    line := "293.1;3;[ 1, 1 ];[ 2, 0 ];[ 0, 0 ];0;[ 2, 1 ];[ 2, 1 ];[ 0, 2 ];[ 2, 1 ];[ 0, 1 ];[ 2, 2 ];[ 1, 1 ];[ 0, 1 ];[ 2, 0 ];[ 2, 1 ];[ 0, 2 ];[ 0, 1 ];[ 1, 0 ];[2, 0 ];[ 2, 2 ];[ 0, 0 ];[ 0, 0 ];[ 0, 2 ];[ 2, 2 ];[ 1, 2 ];[ 2, 2 ];x^2 + 1";
    primeList := "level;p;2.1;5.1;5.2;9.1;13.1;13.2;17.1;17.2;29.1;29.2;37.1;37.2;41.1;41.2;49.1;53.1;53.2;61.1;61.2;73.1;73.2;89.1;89.2;97.1;97.2";
    
    return CheckNonrationalLift(QuadFld(1), line, primeList);
end function;

function CheckAnotherNonrationalLiftFp2()
    F := QuadFld(11);
    p := 7;
    line := "124.1;7;[ 4, 1 ];[ 0, 5 ];0;[ 2, 6 ];[ 3, 4 ];[ 4, 2 ];[ 1, 1 ];[ 4, 2 ];0;[ 3, 4 ];[ 6, 6 ];[ 1, 2 ];[ 1, 0 ];[ 2, 3 ];0;[ 0, 6 ];[ 0, 4 ];[ 4, 1 ];[ 3, 1 ];[ 5, 0 ];[ 3, 3 ];[ 5, 6 ];[ 1, 0 ];[ 4, 2 ];[ 3, 4 ];[ 6, 2 ];[ 0, 4 ];x^2 + 6*x + 3";
    primeList := Split("3.1;3.2;4.1;5.1;5.2;11.1;23.1;23.2;31.1;31.2;37.1;37.2;47.1;47.2;49.1;53.1;53.2;59.1;59.2;67.1;67.2;71.1;71.2;89.1;89.2;97.1;97.2", ";");
    B := BianchiCohomologySpace(LMFDBIdeal(F,"124.1"), BianchiWeight(F,0,0 : char := p));
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    // return FindLifts(f);
    return FindLifts(f);
   
end function;

function CheckCubicNonrationalLift()
    d := 11;
    F := QuadFld(d);
    p := 3;
    bound := 150;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "265.1"), BianchiWeight(F,0,0 : char := p));
    // B := BianchiCohomologySpace(LMFDBIdeal(F, "355.1"), BianchiWeight(F,0,0 : char := p));
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    for f in Eigenforms(B) do
	FindLifts(f);
    end for;
    return "cope";

end function;

function CheckMultiplicityWeird()
    // TODO: check that there's nothing at same level!
    p := 11;
    F := QuadFld(2);
    line := "89.2;11;1;8;7;0;0;9;10;0;10;9;1;8;4;2;8;6;10;7;2;0;6;4;4;8;0;6;6";
    primeList := Split("2.1;3.1;3.2;11.1;11.2;17.1;17.2;19.1;19.2;25.1;41.1;41.2;43.1;43.2;49.1;59.1;59.2;67.1;67.2;73.1;73.2;83.1;83.2;89.1;89.2;97.1;97.2", ";");
    B := BianchiCohomologySpace(LMFDBIdeal(F, "89.2"), BianchiWeight(F,0,0 : char := p));
    
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    fLift := FindLifts(f);

    newLvl := Level(fLift);
    B := BianchiCohomologySpace(newLvl, BianchiWeight(BaseField(fLift),0,0 : char := p));
    efs := Eigenforms(B);
    assert efs[1]`eigenspaceDim eq 2;
    return 0;
end function;

function CheckLiftableD2()
    p := 41;
    F := QuadFld(2);
    line := "97.1;41;15;11;1;23;39;39;11;33;12;11;0;0;27;35;31;35;29;5;40;22;12;2;30;9;23;0;5";
    primeList := Split("2.1;3.1;3.2;11.1;11.2;17.1;17.2;19.1;19.2;25.1;41.1;41.2;43.1;43.2;49.1;59.1;59.2;67.1;67.2;73.1;73.2;83.1;83.2;89.1;89.2;97.1;97.2", ";");
    B := BianchiCohomologySpace(LMFDBIdeal(F, "97.1"), BianchiWeight(F,0,0 : char := p));
    
    f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
    return FindLifts(f);
end function;

// Look for lifts which sage couldn't find in the lmfdb

/*
The main idea is to do various passes with different intervals
specified by lvlLowerBd and lvlUpperBd. For high levels, it might be a
good idea to set recompute := true, since by default, we only store
eigenvalues up to norm 100.

The output is stored in "./data/irrat_lifts_dX.csv". If no lift is found, it will write the output from FindLifts, telling you if the problem was that no lifts were found, or if there were no level raising primes. 
*/
function LookForLMFDBUnliftable(d : liftLvlLowerBd :=0, liftLvlUpperBd := 10000, recompute := false, heckeBd := 100, lvlMin := 0, lvlMax := 1000)
    F := QuadFld(d);		// NB: Caching this lets us cache char 0 eigenforms.
    input := "data/lmfdbNonlift_d" cat Sprint(d) cat ".csv";
    output := "data/irrat_lifts_d" cat Sprint(d) cat "_v2.csv";
    lines := Split(Read(input), "\n");
    topLine := lines[1];
    topElts := Split(topLine, ";");
    if Read(output) eq "" then 
	fprintf output, "level; prime; lift level;" cat Join(topElts[3..#topElts], ";") cat "\n";
    end if;
    primeLabels := topElts[3..#topElts -3];
    // Helper function: has a lift for this line already been recorded?
    HasFoundLift := function(line, output)
	existingLines := Split(Read(output), "\n");
	lvl := Split(line, ";")[1];
	p := Split(line, ";")[2];
	if #[l : l in lines[2..#lines] | Split(l, ";")[1] eq lvl and Split(l, ";")[2] eq p] gt 1 then
	    return false;
	end if;
	for exLine in existingLines do
	    if Split(exLine, ";")[1] eq lvl and Split(exLine, ";")[2] eq p then
		return "level raising" notin exLine and "None found" notin exLine;
	    end if;
	end for;
	return false;
    end function;
    
    for line in lines[2..#lines] do
	lvl := Split(line, ";")[1];
	Nm := Norm(LMFDBIdeal(F,lvl));

	if lvlMin gt Nm or lvlMax lt Nm then
	    continue;
	end if;
	
	if HasFoundLift(line, output) then
	    print "A lift was already found";
	    continue;
	end if;
	
	print "Looking for lifts of line", line;
	// Returns assarray with eigenvalues (as strings) and metadata;
	res := CheckNonrationalLift(F, line, topLine : lvlLowerBd := liftLvlLowerBd, lvlUpperBd := liftLvlUpperBd, recompute := recompute, heckeBd := heckeBd);
	
	if Type(res) eq Assoc then
	    resultLine := res["lift_level"] cat ";";
	    for lab in primeLabels do
		if lab notin Keys(res) then
		    print "WARNING label", lab, "not found";
		end if;
	    end for;
		
	    resultLine cat:= Join([res[lab] : lab in primeLabels], ";");
	    resultLine cat:= ";" cat res["Coeff_minpoly"];
	    
	else
	    resultLine := Sprint(res);
	end if;
	prime := Split(line, ";")[2];
	resultLine := lvl cat ";" cat prime cat ";" cat resultLine cat "\n";
	if resultLine notin Read(output) then
	    fprintf output, resultLine;
	else
	    print "Result already stored, moving on";
	end if;
	print "\n\n";
    end for;

    return true;
end function;

function LookForAllIrrational(d)
    print "WARNING: this function is old and not adapted to the new format. Do not expect it to work";
    F := QuadFld(d);
    input := "data/nonEis_d" cat Sprint(d) cat ".csv";
    output := "data/irrat_lifts_d" cat Sprint(d) cat ".csv";
    lines := Split(Read(input), "\n");
    topLine := lines[1];
    results := [* *];
    for line in lines[2..#lines] do
	if "[" notin line then
	    continue;
	end if;
	
	id := Split(line, ";")[1] cat ";" cat Split(line, ";")[2] cat ";";
	// As in LookForLMFDBUnliftable: id only identifies the line when no other
	// line shares its level and prime, so otherwise we redo the search.
	if id in Read(output) and #[l : l in lines[2..#lines] | "[" in l and id eq Split(l, ";")[1] cat ";" cat Split(l, ";")[2] cat ";"] eq 1 then
	    continue;
	end if;
	print "Looking for lifts of id", id;
	try 
	    res := CheckNonrationalLift(F, line, topLine);
	catch err
	    print "Failed to initalize class with error", err;
	    continue line;
	end try;
	

	// if Sprint(res) eq "None found" then
	resultLine := id cat Sprint(res) cat "\n";
	if resultLine notin Read(output) then
	    fprintf output, resultLine;
	end if;
	    // else
	    // fprintf output, id cat Sprint(res);
	// end if;
	
    end for;
    return results;
end function;


function CheckNonLR()
    // This doesn't have any level raising factors, at least up to norm 200
    d := 1;
    F := QuadFld(d);
    p := 23;
    bound := 200;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "281.1"), BianchiWeight(F,0,0 : char := p));
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    lifts := [* *];
    for f in Eigenforms(B) do
	Append(~lifts, <f, FindLifts(f : lvlUpperBd := bound, at_p := true)>);
    end for;
    return lifts;
end function;

function CheckDouchebag()
    // This one has small level so it shouldn't be that hard to find lift
    d := 2;
    F := QuadFld(d);
    p := 19;
    bound := 200;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "73.2"), BianchiWeight(F,0,0 : char := p));
    print "Initialized", B;
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    lifts := [* *];
    for f in Eigenforms(B) do
	print "Eigenvalues:", PrintEigenvalues(f : bd := bound);
	Append(~lifts, <f, FindLifts(f)>);
    end for;
    return lifts;

end function;

function CheckDouchebag2( : recompute:=false, bound := 200)
    // This one has small level so it shouldn't be that hard to find lift
    d := 3;
    F := QuadFld(d);
    p := 17;
    label := "277.1";
    B := BianchiCohomologySpace(LMFDBIdeal(F, label), BianchiWeight(F,0,0 : char := p));
    if recompute then
	print "Initialized", B;
	SetHeckeBound(B, bound);
	print "Computing eigenforms with Hecke bound", bound;
	f := Eigenforms(B)[1];
    else
	filename := "data/nonEis_d" cat Sprint(d) cat ".csv";
	lines := Split(Read(filename), "\n");
	primeLine := Split(lines[1], ";");
	primeList := primeLine[3..#primeLine];
	for line in lines do
	    if Split(line, ";")[1] eq label then
		f := ReadClass(line, B, [LMFDBIdeal(F, I) : I in primeList]);
		break;
	    end if;
	end for;

    end if;
    
    lift := FindLifts(f : at_p := false);
    return lift;
end function;

function CheckDouchebag3()
    // This one has small level so it shouldn't be that hard to find lift
    d := 11;
    F := QuadFld(d);
    p := 17;
    bound := 200;
    B := BianchiCohomologySpace(LMFDBIdeal(F, "69.2"), BianchiWeight(F,0,0 : char := p));
    print "Initialized", B;
    SetHeckeBound(B, bound);
    print "Computing eigenforms with Hecke bound", bound;
    lifts := [* *];
    for f in Eigenforms(B) do
	print "Eigenvalues:", EigenvalueList(f);
	Append(~lifts, <f, FindLifts(f)>);
    end for;
    return lifts;

end function;

// turns a line from d*_liftable.csv into its raw data so we can feed it into VerifyLMFDBLift
function UnpackLiftableString(lmfdbstr)
	ss := Split(lmfdbstr,";");
	levelLabel := ss[1];
	p := StringToInteger(ss[2]);
	eigs := [StringToInteger(u) : u in Split(ss[3][2..#ss[3]-1],",")];

	// little utility function to extract the level from a BMF label 
	function BMFLabelToLevel(foo)
		bar := foo[Index(foo,"-")+1..#foo-1];
		return bar[1..Index(bar,"-")-1];
	end function;

	liftlabels := [BMFLabelToLevel(u) : u in Split(ss[4][2..#ss[4]-1],",")];

	return levelLabel,p,eigs,liftlabels;
end function;










// tries to verify a probable lift from LMFDB data via cocycles. `zealous` option 
// checks all of them, rather than quitting once one has been found.
// `careful` option refuses to compute spaces with level more than norm 5000
function VerifyLMFDBLift(d,str : zealous := false, careful := false)
	K := QuadFld(d);
	ZK := MaximalOrder(K);

	levelLabel,p,eigs,liftLabels := UnpackLiftableString(str);

	level1 := LMFDBIdeal(K, levelLabel);

	W1 := BianchiWeight(K, 0, 0 : char := p);
	W2 := BianchiWeight(K, 0, 0);
	B1 := BianchiCohomologySpace(level1, W1);

	s := Split(Read("data/nonEis_d" cat Sprint(d) cat ".csv"),"\n")[1];
	// this cuts out just the part of the string with the labels 
	pp := s[9..#s-14];
	PP := [LMFDBIdeal(K,u) : u in Split(pp,";")];

	// this feels quite silly, having to re-egineer the string.
	fstr := levelLabel cat ";" cat Sprint(p) cat ";" cat &cat[Sprint(u) cat ";" : u in eigs];
	f := ReadClass(fstr,B1,PP);

	if zealous then
		lift_bools := [];
	end if;

	for label in liftLabels do 
		level2 := LMFDBIdeal(K, label);
		if careful and Norm(level2) gt 5000 then
			print "Level norm exceeds sensible bounds, please deactivate careful mode";
		else 

			B2 := BianchiCohomologySpace(level2, W1);
			B3 := BianchiCohomologySpace(level2, W2);

			// this is the level-raise factor 
			D := level2/level1;
			if GCD(level1,D) eq 1*ZK then 
				level_raise_f := [RaiseCocycleLevel(B1,B2,f,dd) : dd in Divisors(D)];
			else 
				level_raise_f := [RaiseCocycleLevelSlow(B1,B2,f,dd) : dd in Divisors(D)];
			end if;
			level_raise_space := sub<B2`forms | [B2`down(ff`Zvector) : ff in level_raise_f]>;

			red := ReductionModPMap(B3, B2);
			red_forms := CharacteristicZeroImage(B2,B3);

			lb := Dimension(level_raise_space meet red_forms) ge 1;

			if zealous then 
				Append(~lift_bools,lb);
			else 
				if lb then 
					return true,label;
				end if;
			end if;
		end if;

	end for;

	if zealous then 
		return lift_bools;
	else 
		return false;
	end if;

end function;


// tries to verify a lift at line number `linenum` in the file d*_liftable.csv
procedure VerifyLift(d,linenum)
	if linenum eq 1 then
		print "Table heading contained on line 1, no form to lift";
	end if;
	K := QuadFld(d);
	ZK := MaximalOrder(K);
	rr := Read("sage/d" cat Sprint(d) cat "_liftable.csv");
	lines := Split(rr);
	filename := "data/verified_d" cat Sprint(d) cat "_" cat Sprint(linenum) cat ".csv";
	SetColumns(0);

	str := lines[linenum];
	levelLabel, p, eigs := Explode(Split(str,";"));
	tt, liftLabel := VerifyLMFDBLift(d,str);
	if tt then 
		outstr := levelLabel cat ";" cat p cat ";" cat liftLabel cat ";" cat eigs;
		Write(filename,outstr);
		printf "%o: Verified lift %o\n", linenum, levelLabel cat ";" cat p cat ";" cat eigs;
	else 
		printf "Failed to verify lift %o\n", str;
	end if;
end procedure;


// checks part 2 of the conjecture for the forms in d*_liftable.csv
procedure CheckConjecture2(d : verbose := false)
	assert d in {1,2,3,7,11};
	rr := Read("sage/d" cat Sprint(d) cat "_liftable.csv");
	rr := Split(rr,"\n");

	// this skips the level 1 mod 2 system over Q(-11), which takes a very long time
	start := 2;
	if d eq 11 then 
		start := 3;
	end if;

	for i in [start..#rr] do 
		form_data := rr[i];
		print Split(form_data,";")[1..2];
		f := LoadForm_liftable(d,form_data);
		K := Parent(f)`field;
		// we gather the ideals where f lifts 
		levelLabel,p,eigs,liftLabels := UnpackLiftableString(form_data);
		
		level := LMFDBIdeal(K,levelLabel);

		lift_ideals := [LMFDBIdeal(K,u) : u in liftLabels];

		for ll in lift_ideals do 
			if verbose then 
				printf "Checking Conjecture (2) on level %o\n", LMFDBLabel(ll);
			end if;
			Q := ll/level;
			PP := [f[1] : f in Factorization(Q)];
			satisfies := true;
			for P in PP do 
				eig := Eigenvalue(f,P);
				sat := (eig^2 - (1+Norm(P))^2) eq 0 or level*p subset P;
				if not sat then 
					if not verbose then
						printf "Problem occurs at level %o, prime label %o\n", LMFDBLabel(ll), LMFDBLabel(P);
					else 
						printf "Problem occurs prime label %o\n", LMFDBLabel(P);
					end if;
					printf "a_P^2 - (1+N(P))^2 = %o\n", eig^2 - (1+Norm(P))^2;
					printf "Prime divides frak(n)*p: %o\n", level*p subset P;
					printf "Valuation of P in level raise factor: %o\n", Valuation(ll/level,P);
					printf "\n";
				end if;
				satisfies and:= sat;
			end for;
			if verbose then 
				printf "All primes in lift factor satisfy Conjecture (2): %o\n\n", satisfies;
			end if;
		end for;
		if verbose then 
			print "";
		end if;
	end for;
end procedure;



function CheckEtheralData()
	d := 1;
	K := QuadFld(d);
	ZK := MaximalOrder(K);

	rr := Read("data/nonEis_d1.csv");
	data := Split(rr,"\n");

	primeLabels := data[1][8..#data[1]-14];
	primeList := [LMFDBIdeal(K,u) : u in Split(primeLabels,";")];

	// we check each row of the file for forms wrongly marked as ethereal 
	for e in data[2..#data] do 
		ss := Split(e,";");
		level := LMFDBIdeal(K,ss[1]);
		p := StringToInteger(ss[2]);
		B := BianchiCohomologySpace(level,BianchiWeight(K,0,0 : char := p));
		B0 := BianchiCohomologySpace(level,BianchiWeight(K,0,0));
		f := ReadClass(e,B,primeList);
		if not HasEtherealEigenvalues(B0,f) then 
			print "Eigenvalue system falsely labelled ethereal";
		else 
			print "Eigenvalue system is ethereal";
		end if;
		print e;
		print "";
	end for;

end function;

